name: Build PyWarp v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true

jobs:
  build-windows:
    name: Build PyWarp Windows v${{ inputs.version }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka==1.9.5

      - name: Build Executable (Windows)
        shell: pwsh
        run: |
          $version = "${{ inputs.version }}"
          $output = "pywarp-windows-v$version.exe"
          $env:NUITKA_DEPENDENCY_SCAN = "1"

          python -m nuitka `
            main.py `
            --standalone `
            --onefile `
            --disable-console `
            --enable-plugin=pyside6 `
            --nofollow-imports `
            --noinclude-pytest-mode=nofollow `
            --noinclude-unittest-mode=nofollow `
            --nofollow-import-to=tkinter,test,pydoc `
            --include-data-dir=assets=assets `
            --include-qt-plugins=all `
            --windows-icon-from-ico=assets/logo.ico `
            --output-dir=dist `
            --output-filename="pywarp-windows-v$version" `
            --windows-company-name="PyWarp" `
            --windows-product-name="PyWarp" `
            --windows-file-version="$version" `
            --windows-product-version="$version" `
            --remove-output `
            --assume-yes-for-downloads

      - name: Upload Executable (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: pywarp-windows-v${{ inputs.version }}
          path: dist/pywarp-windows-v${{ inputs.version }}.exe

  build-linux-macos:
    name: Build PyWarp ${{ matrix.os }} v${{ inputs.version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: build-windows
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka==1.9.5

      - name: Build Executable (Linux/macOS)
        shell: bash
        run: |
          VERSION="${{ inputs.version }}"
          PLATFORM="${{ matrix.os }}"
          OUTPUT="pywarp-${PLATFORM}-v$VERSION"

          FLAGS="--standalone --onefile --remove-output --disable-console --enable-plugin=pyside6"
          if [[ "$PLATFORM" == "macos-latest" ]]; then
            FLAGS+=" --macos-app-icon=assets/logo.icns --macos-create-app-bundle"
          fi

          python -m nuitka \
            main.py \
            $FLAGS \
            --include-data-dir=assets=assets \
            --output-filename="$OUTPUT"

      - name: Make Executable (Linux/macOS)
        run: chmod +x pywarp-${{ matrix.os }}-v${{ inputs.version }}

      - name: Upload Executable (Linux/macOS)
        uses: actions/upload-artifact@v4
        with:
          name: pywarp-${{ matrix.os }}-v${{ inputs.version }}
          path: pywarp-${{ matrix.os }}-v${{ inputs.version }}

  release:
    name: Release PyWarp v${{ inputs.version }}
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux-macos]
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Check if Tag Exists
        id: check_tag
        run: |
          TAG="v${{ inputs.version }}"
          EXISTS=$(gh release view "$TAG" --json tagName --jq '.tagName' || echo "")
          echo "exists=$EXISTS" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release
        run: |
          VERSION="${{ inputs.version }}"
          TAG="v$VERSION"
          if [ "${{ steps.check_tag.outputs.exists }}" = "$TAG" ]; then
            echo "Updating existing release..."
            gh release upload "$TAG" release-assets/** --clobber
          else
            echo "Creating new draft release..."
            gh release create "$TAG" release-assets/** --title "PyWarp v$VERSION" --draft
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
