name: Build PyWarp Executables (Windows, Linux, macOS)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read Version
        id: version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Nuitka and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt || true
        shell: bash

      ###############################################
      # WINDOWS BUILD
      ###############################################
      - name: Build Executable with Nuitka (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $output = "pywarp-windows-latest-v$version.exe"

          $env:NUITKA_DEPENDENCY_SCAN = "1"

          python -m nuitka `
            --onefile `
            --standalone `
            --nofollow-imports `
            --remove-output `
            --disable-console `
            --enable-plugin=pyside6 `
            --windows-icon-from-ico=assets/logo.ico `
            --assume-yes-for-downloads `
            --output-filename="pywarp-windows-latest-v$version" `
            --product-name="PyWarp" `
            --company-name="Saeed MSS" `
            --file-description="PyWarp - Cloudflare Warp GUI" `
            --version-string="$version" `
            --product-version="$version" `
            --file-version="$version" `
            --copyright="© 2025 Saeed MSS" `
            main.py

          if (!(Test-Path $output)) {
            Write-Host "ERROR: Executable not created"
            exit 1
          }

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pywarp-windows
          path: pywarp-windows-latest-v${{ steps.version.outputs.version }}.exe

      ###############################################
      # LINUX / MACOS BUILD
      ###############################################
      - name: Build Executable with Nuitka (Linux/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PLATFORM="${{ matrix.os }}"
          OUTPUT="pywarp-${PLATFORM}-v$VERSION"

          ICON=""
          if [[ "$PLATFORM" == "macos-latest" ]]; then
            ICON="--macos-app-icon=assets/logo.icns"
          fi

          python -m nuitka \
            --onefile \
            --standalone \
            --nofollow-imports \
            --remove-output \
            --disable-console \
            --enable-plugin=pyside6 \
            $ICON \
            --assume-yes-for-downloads \
            --output-filename="$OUTPUT" \
            --product-version="$VERSION" \
            --file-version="$VERSION" \
            main.py

      - name: Set Executable Permissions (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: chmod +x pywarp-${{ matrix.os }}-v${{ steps.version.outputs.version }}

      - name: Upload Artifact (Linux/macOS)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pywarp-${{ matrix.os }}
          path: pywarp-${{ matrix.os }}-v${{ steps.version.outputs.version }}
